# Generated by Django 5.1 on 2024-09-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_students_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
